
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ= #mot de passe encodé en base64

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_USER: "admin"
  POSTGRES_DB: "storedb"
  POSTGRES_HOST_AUTH_METHOD: "trust"

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
data:
  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"

---

apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: cm9vdA== #mot de passe encodé en base64