# Default values for HELM.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: helm

fastapi:
  name: fastapi
  replicaCount: 3
  image:
    repository: zzouhal/fastapi
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 5000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-k8s
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: website.zz.cloudns.ph
      paths:
        - path: /
          pathType: Prefix
          service:
            name: fastapi
            port: 5000
  tls:
   - secretName: letsencrypt-secret
     hosts:
       - website.zz.cloudns.ph

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
- name: postgres-data
  persistentVolumeClaim:
    claimName: postgres-data

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: postgres-data
  mountPath: "/var/lib/postgresql/data"
  #readOnly: true

db:
  name: db
  replicaCount: 1
  image:
    repository: postgres:12.0-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  config:
    secret: db-secret
    configmap: db-config
  pv:
    name: helm-pv
    storage: 10Gi
    hostpath: "/mnt/data/helm"
  pvc:
    name: postgres-data
    storage: 100Mi



pgadmin:
  name: pgadmin
  replicaCount: 1
  image:
    repository: dpage/pgadmin4
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    targetport: 80
  config:
    secret: pg-secret
    configmap: pg-config